name: CI

on:
    push:
        branches:
            - main
            - develop
            - '*'
    pull_request:

permissions:
    contents: read

jobs:
    test:
        name: Test on Python ${{ matrix.python-version }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [3.10, 3.11, 3.12, 3.13]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Set up uv
              uses: astral-sh/setup-uv@v1

            - name: Install Hatch and Poe
              run: uv pip install hatch poethepoet

            - name: Run tests
              run: poe test
