name: Publish to PyPI

on:
    push:
        tags:
            - 'v*.*.*' # Trigger on version tags like v1.2.3

permissions:
    id-token: write # Required for PyPI Trusted Publishing
    contents: read
jobs:
    test-and-publish:
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/pypdfmake
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  python-version: '3.10'

            - name: Install the project
              run: uv sync --all-extras --dev

            - name: Enable caching
              uses: astral-sh/setup-uv@v5
              with:
                  cache: true

            - name: Run tests
              run: uv run poe test-no-watch

            - name: Create release package
              run: uv build
            - name: Upload to PyPI
              uses: pypa/gh-action-pypi-publish@v1
