name: Release

on:
    push:
        branches: [main]

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install uv and set the python version
              uses: astral-sh/setup-uv@v5
              with:
                  python-version: '3.10'

            - name: Install the project
              run: uv sync --all-extras --dev

            - name: Test the project
              run: poe test-no-watch

            - name: Build project
              run: uv build

            - name: Debug build directory
              run: ls -la .

            - name: Get version
              id: version
              run: echo "version=$(uv run hatch version)" >> $GITHUB_OUTPUT

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ steps.version.outputs.version }}
                  release_name: Release v${{ steps.version.outputs.version }}
                  draft: false
                  prerelease: false

            - name: Upload wheel
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./dist/*.whl
                  asset_name: pypdfmake-${{ steps.version.outputs.version }}-py3-none-any.whl
                  asset_content_type: application/zip

            - name: Upload source distribution
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./dist/*.tar.gz
                  asset_name: pypdfmake-${{ steps.version.outputs.version }}.tar.gz
                  asset_content_type: application/gzip
